### ISSUE TITLE
flinkhose deploy - ClientError: An error occurred (NoSuchEntity) when calling the GetRole operation: Unknown

### ISSUE THREAD

**Issue by KingOfPoptart** [DemandCube/flinkhose#50]
```Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/zappa/cli.py", line 1847, in handle
    sys.exit(cli.handle())
  File "/usr/local/lib/python2.7/site-packages/zappa/cli.py", line 345, in handle
    self.dispatch_command(self.command, environment)
  File "/usr/local/lib/python2.7/site-packages/zappa/cli.py", line 377, in dispatch_command
    self.deploy()
  File "/usr/local/lib/python2.7/site-packages/zappa/cli.py", line 474, in deploy
    memory_size=self.memory_size)
  File "/usr/local/lib/python2.7/site-packages/zappa/zappa.py", line 636, in create_lambda_function
    self.get_credentials_arn()
  File "/usr/local/lib/python2.7/site-packages/zappa/zappa.py", line 1509, in get_credentials_arn
    self.credentials_arn = role.arn
  File "/usr/local/lib/python2.7/site-packages/boto3/resources/factory.py", line 339, in property_loader
    self.load()
  File "/usr/local/lib/python2.7/site-packages/boto3/resources/factory.py", line 505, in do_action
    response = action(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 251, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 537, in _make_api_call
    raise ClientError(parsed_response, operation_name)
ClientError: An error occurred (NoSuchEntity) when calling the GetRole operation: Unknown

==============

Need help? Found a bug? Let us know! :D
File bug reports on GitHub here: https://github.com/Miserlou/Zappa
And join our Slack channel here: https://slack.zappa.io
Love!,
 ~ Team Zappa!

Fatal error: local() encountered an error (return code 255) while executing 'zappa deploy'

Aborting.
```

flinkhose_config.yml:

```
components:
  DataCollector:
    app_function: data_collector.collect
    type: LambdaComponent
  Druid:
    type: EC2Component
  EMR:
    job: flinkjob.jar
    schema: EMR.template
    service_role: DataPipelineDefaultRole
    subnet: subnet-0cee147a
    type: EMRComponent
  Firehose:
    schema: Firehose.template
    type: FirehoseComponent
  Heartbeat:
    app_function: heartbeat_app.beat
    events:
    - expression: rate(6 hours)
      function: heartbeat_app.beat
    schema: EMR.template
    type: LambdaComponent
  IndexTable:
    schema: IndexDB.template
    type: DynamoDBComponent
  Indexer:
    app_function: indexer_app.index
    events:
    - event_source:
        arn: arn:aws:s3:::{}
        events:
        - s3:ObjectCreated:*
      function: indexer_app.index
    type: LambdaComponent
data_bucket: flink-test-data
project_name: flink-test
role_name: flink-test-execution-role
stream_name: flink-test-stream
table_name: flink-test-metadata
upload_bucket: flink-test-uploads
```

**Comment by maebert** [comment]
Remove `role_name` from config and / or fix #48
